var rule = {
		"主页url": "https://haoxi.vip/",
		"简介": "简介：&&</li>",
		"导演": "导演：&&</li>",
		"主演": "主演：&&</li>",
		"影片状态": "状态：&&</li>",
		"影片类型": "类型：&&</li>",
		"影片地区": "地区：&&</li>",
		"影片年代": "年份：&&</li>",
		"嗅探词": "aliyuncs.com#.m3u8?#m3u8",
		"数组": "_self\" class=\"public-list-exp\"&&</div>",
		"标题": "title=\"&&\"",
		"副标题": "public-list-prb hide ft2\">&&</span>",
		"图片": "data-src=\"&&\"",
		"搜索url": "https://haoxi.vip/vodsearch/{wd}----------1---/",
		"搜索数组": "a target=\"_self\" class=\"public-list-exp\"&&thumb-else cor5 hide\">",
		"搜索标题": "<a target=\"_self\" href=*>&&</a>",
		"搜索副标题": "public-list-prb hide ft2\">&&</span>",
		"搜索图片": "data-src=\"&&\"",
		"线路数组": "<i class=\"fa ds-dianying\">&&/a>",
		"线路标题": "</i>LLTV<",
		"播放数组": "<ul class=\"anthology-list-play size\"&&</ul>",
		"播放标题": ">&&</a>",
		"播放列表": "<li&&</li>",
		"线路二次截取": "<div class=\"swiper-wrapper\"&&</div>",
		"分类url": "https://haoxi.vip/vodshow/{cateId}-{area}-{by}-{class}-{lang}----{catePg}---{year}/;;a",
		"分类": "电影$1#连续剧$2#综艺$3#动漫$4#短剧$60#电影解说$43"
      }